version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install firebase-tools
          command: sudo npm install -g firebase-tools
      - run:
          name: install nuxt
          command: npm install nuxt
      - run:
          name: build project
          command: npm run build
      ##- run:
          ##name: Deploy Firebase Hosting
          ##command: firebase deploy ##--token "$FIREBASE_TOKEN"
workflows:
  version: 2
  test:
    jobs:
      - test:
